algoritmo "semnome"

var
    N, F: inteiro
    
Funcao Fatorial (V: inteiro) : inteiro
var
 C,R: Inteiro
inicio
    R <- 1
     Para C <- 1 ate v faca
     R <- R * C
   FimPara
   Retorne R
FimFuncao
inicio
 Escreval("จจจจจจจจจจจจจจจจจจจจจจจจจจ")
 Escreval("   Fatorial com fun็ใo    ")
 Escreval("จจจจจจจจจจจจจจจจจจจจจจจจจจ")
      Escreva ("Digite um n๚mero: ")
      Leia (N)
      F <- Fatorial (N)
      Escreval ("O valor de", N, " ้ igual a ", F)
fimalgoritmo
